In [1]:
import torch

# 2.1 Data Manipulation

2.1.8 Exercises
    
2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [2]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(6).reshape(2, 1, 3)
c = torch.arange(2).reshape(1, 2)
a, c, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]))

In [3]:
print(a + c)
print(a + b) # (3,1)+(2,3,1)=(2,3,1); (3,1)+(2,1,3)=(2,3,3); (3,1)+(1,2,3) error
'''
broadcast mechanism:
https://zhuanlan.zhihu.com/p/86997775
'''

tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([[[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4]],

        [[3, 4, 5],
         [4, 5, 6],
         [5, 6, 7]]])


'\nbroadcast mechanism:\nhttps://zhuanlan.zhihu.com/p/86997775\n'